testname: webMUSHRA Example
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Audio evaluation of call quality in windy conditions
    - type: mushra
      id: trial1
      name: MUSHRA
      content: Here you will listen to some clips of phone calls recorded through different headphones in a windy environment. Please rate them on how well you can make understand what is said.<br/>Basic Audio Quality is a single and global attribute that is used to judge any and all detected differences between the reference and the condition.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/A.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/B.wav
          C2: configs/resources/audio/C.wav
          C3: configs/resources/audio/D.wav
    - 
          - random
          - type: mushra
            id: trial_random_1
            name: MUSHRA - Random 2
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/A.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/C.wav
                C2: configs/resources/audio/D.wav
                C3: configs/resources/audio/E.wav          
          - type: mushra
            id: trial_random_2
            name: MUSHRA - Random 1
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/A.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/B.wav
                C2: configs/resources/audio/C.wav
                C3: configs/resources/audio/D.wav          
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
